//searching 5 day weather forecast for city
export const FETCH_WEATHER_SEARCH_PENDING = 'FETCH_WEATHER_SEARCH_PENDING';
export const FETCH_WEATHER_SEARCH_ERROR = 'FETCH_WEATHER_SEARCH_ERROR';
export const FETCH_WEATHER_SEARCH_SUCCESS = 'FETCH_WEATHER_SEARCH_SUCCESS';

//remove city
export const REMOVE_CITY = 'REMOVE_CITY';